spring.application.name=businessdomain-customer
# disabling the swagger-ui
springdoc.swagger-ui.enabled=true
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger.html
# springdoc.api-docs.path=/v3/api-docs
# springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081
custom.activeprofileName=local

# para la conexión a BBDD con spring boot
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:customer
spring.datasource.username=sa
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true

# servidor de Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.db.enabled=true
management.health.db.show-details=always
management.health.defaults.enabled=true
management.health.defaults.show-details=always
management.health.defaults.status.order=DOWN, OUT_OF_SERVICE, UP, UNKNOWN
