spring.config.import=common.properties

#propiedades concretas de producto en cualquier configuración
spring.application.name=businessdomain-product

# para la conexión a BBDD con spring boot
spring.datasource.url=jdbc:h2:mem:product

#propiedades específicas de configuración de producto en local
server.port=8083
custom.activeprofileName=local
