## YAML Template.
---
spring:
    config:
        import: product-common.properties

#propiedades específicas de configuración de producto en desarrollo
server:
    port: 49153

custom:
    activeprofileName: production
    
# End of the file
